version: "3"

services:
    client:
        image: nginx
        ports:
            - 8000:8000
        volumes:
            - ./src:/var/www/html
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./logs:/etc/nginx/logs